name: Validate
on:
  push:
    paths:
      - "default/**"
      - "data/**"
      - "package.json"
  pull_request:
    paths:
      - "default/**"
      - "data/**"
      - "package.json"

jobs:
  validate:
    uses: JacobPEvans/.github/.github/workflows/_cribl-pack-validate.yml@main
    with:
      pack-type: edge
